version: '3.8'

services:
  localstack:
    image: localstack/localstack:1.1
    network_mode: bridge
    environment:
      - AWS_DEFAULT_REGION=sa-east-1
      - SERVICES=sns,sqs,dynamodb
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - '4566:4566'
